FROM owncloud/ubuntu:18.04-amd64@sha256:1d9c91b1b648e8ff2307ebe5a68ab2da739f6e8cad792c9b93446152be168d29

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Smashbox" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/smashbox" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/smashbox" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/smashbox"

ENTRYPOINT ["/usr/local/bin/smash-wrapper"]

RUN apt-get update -y && \
  apt-get install -y \
    git \
    python-pip && \
  git clone --depth 1 https://github.com/owncloud/smashbox.git /smashbox && \
  cd /smashbox && \
  pip install -r requirements.txt && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/*

COPY ./overlay /
WORKDIR /smashbox
